/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace EconomyModel {
  export type PurchaseRecordStruct = {
    buyer: AddressLike;
    level: BigNumberish;
    price: BigNumberish;
    purchasedAt: BigNumberish;
    isWrapped: boolean;
    unlockTime: BigNumberish;
  };

  export type PurchaseRecordStructOutput = [
    buyer: string,
    level: bigint,
    price: bigint,
    purchasedAt: bigint,
    isWrapped: boolean,
    unlockTime: bigint
  ] & {
    buyer: string;
    level: bigint;
    price: bigint;
    purchasedAt: bigint;
    isWrapped: boolean;
    unlockTime: bigint;
  };
}

export interface EconomyModelInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_PRICE_CORE"
      | "BASE_PRICE_REGULAR"
      | "BASE_PRICE_SUB"
      | "BUYBACK_SHARE"
      | "CORE_LOCK_PERIOD"
      | "ECOSYSTEM_SHARE"
      | "MAX_CORE_NODES"
      | "MAX_REGULAR_NODES"
      | "MAX_SUB_NODES"
      | "PRICE_ADJUSTMENT_FACTOR"
      | "PRICE_MAX_PREMIUM"
      | "PRICE_MIN_DISCOUNT"
      | "REGULAR_LOCK_PERIOD"
      | "RESERVE_SHARE"
      | "SUB_LOCK_PERIOD"
      | "TEAM_SHARE"
      | "WRAPPED_LOCK_EXTENSION"
      | "baseDemand"
      | "batchPurchase"
      | "batchSetBlacklist"
      | "blacklist"
      | "blacklistEnabled"
      | "buybackWallet"
      | "checkCompliance"
      | "coreNodeSold"
      | "currentPhase"
      | "demandOffset"
      | "distributeRevenue"
      | "ecosystemWallet"
      | "emergencyWithdraw"
      | "endSale"
      | "getAllPrices"
      | "getCurrentPrice"
      | "getQuotaStatus"
      | "getRevenueDistributionPreview"
      | "getUserPurchaseCount"
      | "getUserPurchases"
      | "isWrappedToken"
      | "lastPriceUpdate"
      | "owner"
      | "priceMultiplier"
      | "priceUpdateInterval"
      | "purchaseHistory"
      | "purchaseSpark"
      | "regularNodeSold"
      | "renounceOwnership"
      | "reserveWallet"
      | "setBlacklist"
      | "setBlacklistEnabled"
      | "setPriceMultiplier"
      | "setPriceUpdateInterval"
      | "sparkNFTAddress"
      | "startSale"
      | "subNodeSold"
      | "teamWallet"
      | "totalNodesSold"
      | "totalRevenue"
      | "transferOwnership"
      | "updateWallets"
      | "usdtToken"
      | "userPurchases"
      | "wrappedTokenCount"
      | "wrappedTokens"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BlacklistUpdated"
      | "ComplianceCheck"
      | "DynamicPricingEnabled"
      | "OwnershipTransferred"
      | "PriceUpdated"
      | "RevenueDistributed"
      | "SaleEnded"
      | "SaleStarted"
      | "SparkPurchased"
      | "TokenLocked"
      | "TokenUnlocked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_PRICE_CORE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASE_PRICE_REGULAR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASE_PRICE_SUB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BUYBACK_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CORE_LOCK_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ECOSYSTEM_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_CORE_NODES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_REGULAR_NODES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SUB_NODES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICE_ADJUSTMENT_FACTOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICE_MAX_PREMIUM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICE_MIN_DISCOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REGULAR_LOCK_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESERVE_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUB_LOCK_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TEAM_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WRAPPED_LOCK_EXTENSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baseDemand",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchPurchase",
    values: [BigNumberish[], boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSetBlacklist",
    values: [AddressLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buybackWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkCompliance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "coreNodeSold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentPhase",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "demandOffset",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ecosystemWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "endSale", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllPrices",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuotaStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRevenueDistributionPreview",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPurchaseCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPurchases",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWrappedToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastPriceUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceMultiplier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "priceUpdateInterval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseHistory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseSpark",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "regularNodeSold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBlacklist",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setBlacklistEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceUpdateInterval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sparkNFTAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startSale",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subNodeSold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "teamWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalNodesSold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWallets",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdtToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userPurchases",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "wrappedTokenCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "wrappedTokens",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_PRICE_CORE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASE_PRICE_REGULAR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASE_PRICE_SUB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BUYBACK_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CORE_LOCK_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ECOSYSTEM_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_CORE_NODES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_REGULAR_NODES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SUB_NODES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_ADJUSTMENT_FACTOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_MAX_PREMIUM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_MIN_DISCOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REGULAR_LOCK_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESERVE_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUB_LOCK_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TEAM_SHARE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "WRAPPED_LOCK_EXTENSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "baseDemand", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchPurchase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSetBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "blacklist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blacklistEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buybackWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkCompliance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "coreNodeSold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "demandOffset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ecosystemWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endSale", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuotaStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRevenueDistributionPreview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPurchaseCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPurchases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWrappedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPriceUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceUpdateInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseSpark",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "regularNodeSold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBlacklistEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceUpdateInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sparkNFTAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startSale", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subNodeSold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "teamWallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalNodesSold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdtToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userPurchases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wrappedTokenCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wrappedTokens",
    data: BytesLike
  ): Result;
}

export namespace BlacklistUpdatedEvent {
  export type InputTuple = [account: AddressLike, status: boolean];
  export type OutputTuple = [account: string, status: boolean];
  export interface OutputObject {
    account: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceCheckEvent {
  export type InputTuple = [buyer: AddressLike, passed: boolean];
  export type OutputTuple = [buyer: string, passed: boolean];
  export interface OutputObject {
    buyer: string;
    passed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DynamicPricingEnabledEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [
    oldMultiplier: BigNumberish,
    newMultiplier: BigNumberish
  ];
  export type OutputTuple = [oldMultiplier: bigint, newMultiplier: bigint];
  export interface OutputObject {
    oldMultiplier: bigint;
    newMultiplier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevenueDistributedEvent {
  export type InputTuple = [
    totalAmount: BigNumberish,
    teamAmount: BigNumberish,
    ecosystemAmount: BigNumberish,
    buybackAmount: BigNumberish,
    reserveAmount: BigNumberish
  ];
  export type OutputTuple = [
    totalAmount: bigint,
    teamAmount: bigint,
    ecosystemAmount: bigint,
    buybackAmount: bigint,
    reserveAmount: bigint
  ];
  export interface OutputObject {
    totalAmount: bigint;
    teamAmount: bigint;
    ecosystemAmount: bigint;
    buybackAmount: bigint;
    reserveAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SaleEndedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SaleStartedEvent {
  export type InputTuple = [phase: BigNumberish];
  export type OutputTuple = [phase: bigint];
  export interface OutputObject {
    phase: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SparkPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    tokenId: BigNumberish,
    level: BigNumberish,
    price: BigNumberish,
    isWrapped: boolean
  ];
  export type OutputTuple = [
    buyer: string,
    tokenId: bigint,
    level: bigint,
    price: bigint,
    isWrapped: boolean
  ];
  export interface OutputObject {
    buyer: string;
    tokenId: bigint;
    level: bigint;
    price: bigint;
    isWrapped: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenLockedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    tokenId: BigNumberish,
    unlockTime: BigNumberish,
    isWrapped: boolean
  ];
  export type OutputTuple = [
    buyer: string,
    tokenId: bigint,
    unlockTime: bigint,
    isWrapped: boolean
  ];
  export interface OutputObject {
    buyer: string;
    tokenId: bigint;
    unlockTime: bigint;
    isWrapped: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenUnlockedEvent {
  export type InputTuple = [buyer: AddressLike, tokenId: BigNumberish];
  export type OutputTuple = [buyer: string, tokenId: bigint];
  export interface OutputObject {
    buyer: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EconomyModel extends BaseContract {
  connect(runner?: ContractRunner | null): EconomyModel;
  waitForDeployment(): Promise<this>;

  interface: EconomyModelInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_PRICE_CORE: TypedContractMethod<[], [bigint], "view">;

  BASE_PRICE_REGULAR: TypedContractMethod<[], [bigint], "view">;

  BASE_PRICE_SUB: TypedContractMethod<[], [bigint], "view">;

  BUYBACK_SHARE: TypedContractMethod<[], [bigint], "view">;

  CORE_LOCK_PERIOD: TypedContractMethod<[], [bigint], "view">;

  ECOSYSTEM_SHARE: TypedContractMethod<[], [bigint], "view">;

  MAX_CORE_NODES: TypedContractMethod<[], [bigint], "view">;

  MAX_REGULAR_NODES: TypedContractMethod<[], [bigint], "view">;

  MAX_SUB_NODES: TypedContractMethod<[], [bigint], "view">;

  PRICE_ADJUSTMENT_FACTOR: TypedContractMethod<[], [bigint], "view">;

  PRICE_MAX_PREMIUM: TypedContractMethod<[], [bigint], "view">;

  PRICE_MIN_DISCOUNT: TypedContractMethod<[], [bigint], "view">;

  REGULAR_LOCK_PERIOD: TypedContractMethod<[], [bigint], "view">;

  RESERVE_SHARE: TypedContractMethod<[], [bigint], "view">;

  SUB_LOCK_PERIOD: TypedContractMethod<[], [bigint], "view">;

  TEAM_SHARE: TypedContractMethod<[], [bigint], "view">;

  WRAPPED_LOCK_EXTENSION: TypedContractMethod<[], [bigint], "view">;

  baseDemand: TypedContractMethod<[], [bigint], "view">;

  batchPurchase: TypedContractMethod<
    [levels: BigNumberish[], isWrapped: boolean[]],
    [void],
    "nonpayable"
  >;

  batchSetBlacklist: TypedContractMethod<
    [accounts: AddressLike[], status: boolean],
    [void],
    "nonpayable"
  >;

  blacklist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  blacklistEnabled: TypedContractMethod<[], [boolean], "view">;

  buybackWallet: TypedContractMethod<[], [string], "view">;

  checkCompliance: TypedContractMethod<[buyer: AddressLike], [boolean], "view">;

  coreNodeSold: TypedContractMethod<[], [bigint], "view">;

  currentPhase: TypedContractMethod<[], [bigint], "view">;

  demandOffset: TypedContractMethod<[], [bigint], "view">;

  distributeRevenue: TypedContractMethod<[], [void], "nonpayable">;

  ecosystemWallet: TypedContractMethod<[], [string], "view">;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  endSale: TypedContractMethod<[], [void], "nonpayable">;

  getAllPrices: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        regularPrice: bigint;
        subPrice: bigint;
        corePrice: bigint;
      }
    ],
    "view"
  >;

  getCurrentPrice: TypedContractMethod<[level: BigNumberish], [bigint], "view">;

  getQuotaStatus: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        coreAvailable: bigint;
        subAvailable: bigint;
        regularAvailable: bigint;
        coreSold: bigint;
        subSold: bigint;
        regularSold: bigint;
      }
    ],
    "view"
  >;

  getRevenueDistributionPreview: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        balance: bigint;
        teamAmount: bigint;
        ecosystemAmount: bigint;
        buybackAmount: bigint;
        reserveAmount: bigint;
      }
    ],
    "view"
  >;

  getUserPurchaseCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserPurchases: TypedContractMethod<
    [user: AddressLike],
    [EconomyModel.PurchaseRecordStructOutput[]],
    "view"
  >;

  isWrappedToken: TypedContractMethod<
    [tokenId: BigNumberish],
    [boolean],
    "view"
  >;

  lastPriceUpdate: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  priceMultiplier: TypedContractMethod<[], [bigint], "view">;

  priceUpdateInterval: TypedContractMethod<[], [bigint], "view">;

  purchaseHistory: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean, bigint] & {
        buyer: string;
        level: bigint;
        price: bigint;
        purchasedAt: bigint;
        isWrapped: boolean;
        unlockTime: bigint;
      }
    ],
    "view"
  >;

  purchaseSpark: TypedContractMethod<
    [level: BigNumberish, isWrapped: boolean],
    [void],
    "nonpayable"
  >;

  regularNodeSold: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reserveWallet: TypedContractMethod<[], [string], "view">;

  setBlacklist: TypedContractMethod<
    [account: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  setBlacklistEnabled: TypedContractMethod<
    [enabled: boolean],
    [void],
    "nonpayable"
  >;

  setPriceMultiplier: TypedContractMethod<
    [_multiplier: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPriceUpdateInterval: TypedContractMethod<
    [_interval: BigNumberish],
    [void],
    "nonpayable"
  >;

  sparkNFTAddress: TypedContractMethod<[], [string], "view">;

  startSale: TypedContractMethod<[phase: BigNumberish], [void], "nonpayable">;

  subNodeSold: TypedContractMethod<[], [bigint], "view">;

  teamWallet: TypedContractMethod<[], [string], "view">;

  totalNodesSold: TypedContractMethod<[], [bigint], "view">;

  totalRevenue: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateWallets: TypedContractMethod<
    [
      _teamWallet: AddressLike,
      _ecosystemWallet: AddressLike,
      _buybackWallet: AddressLike,
      _reserveWallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  usdtToken: TypedContractMethod<[], [string], "view">;

  userPurchases: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  wrappedTokenCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  wrappedTokens: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_PRICE_CORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BASE_PRICE_REGULAR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BASE_PRICE_SUB"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BUYBACK_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CORE_LOCK_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ECOSYSTEM_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_CORE_NODES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_REGULAR_NODES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SUB_NODES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_ADJUSTMENT_FACTOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_MAX_PREMIUM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_MIN_DISCOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REGULAR_LOCK_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RESERVE_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SUB_LOCK_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TEAM_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WRAPPED_LOCK_EXTENSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseDemand"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchPurchase"
  ): TypedContractMethod<
    [levels: BigNumberish[], isWrapped: boolean[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchSetBlacklist"
  ): TypedContractMethod<
    [accounts: AddressLike[], status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "blacklist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "blacklistEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "buybackWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "checkCompliance"
  ): TypedContractMethod<[buyer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "coreNodeSold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentPhase"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "demandOffset"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "distributeRevenue"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ecosystemWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "endSale"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllPrices"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        regularPrice: bigint;
        subPrice: bigint;
        corePrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentPrice"
  ): TypedContractMethod<[level: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getQuotaStatus"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        coreAvailable: bigint;
        subAvailable: bigint;
        regularAvailable: bigint;
        coreSold: bigint;
        subSold: bigint;
        regularSold: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRevenueDistributionPreview"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        balance: bigint;
        teamAmount: bigint;
        ecosystemAmount: bigint;
        buybackAmount: bigint;
        reserveAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPurchaseCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserPurchases"
  ): TypedContractMethod<
    [user: AddressLike],
    [EconomyModel.PurchaseRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isWrappedToken"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastPriceUpdate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceMultiplier"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "priceUpdateInterval"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "purchaseHistory"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean, bigint] & {
        buyer: string;
        level: bigint;
        price: bigint;
        purchasedAt: bigint;
        isWrapped: boolean;
        unlockTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "purchaseSpark"
  ): TypedContractMethod<
    [level: BigNumberish, isWrapped: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "regularNodeSold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reserveWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setBlacklist"
  ): TypedContractMethod<
    [account: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBlacklistEnabled"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceMultiplier"
  ): TypedContractMethod<[_multiplier: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceUpdateInterval"
  ): TypedContractMethod<[_interval: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sparkNFTAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "startSale"
  ): TypedContractMethod<[phase: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subNodeSold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "teamWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalNodesSold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRevenue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateWallets"
  ): TypedContractMethod<
    [
      _teamWallet: AddressLike,
      _ecosystemWallet: AddressLike,
      _buybackWallet: AddressLike,
      _reserveWallet: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdtToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userPurchases"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "wrappedTokenCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "wrappedTokens"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getEvent(
    key: "BlacklistUpdated"
  ): TypedContractEvent<
    BlacklistUpdatedEvent.InputTuple,
    BlacklistUpdatedEvent.OutputTuple,
    BlacklistUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceCheck"
  ): TypedContractEvent<
    ComplianceCheckEvent.InputTuple,
    ComplianceCheckEvent.OutputTuple,
    ComplianceCheckEvent.OutputObject
  >;
  getEvent(
    key: "DynamicPricingEnabled"
  ): TypedContractEvent<
    DynamicPricingEnabledEvent.InputTuple,
    DynamicPricingEnabledEvent.OutputTuple,
    DynamicPricingEnabledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RevenueDistributed"
  ): TypedContractEvent<
    RevenueDistributedEvent.InputTuple,
    RevenueDistributedEvent.OutputTuple,
    RevenueDistributedEvent.OutputObject
  >;
  getEvent(
    key: "SaleEnded"
  ): TypedContractEvent<
    SaleEndedEvent.InputTuple,
    SaleEndedEvent.OutputTuple,
    SaleEndedEvent.OutputObject
  >;
  getEvent(
    key: "SaleStarted"
  ): TypedContractEvent<
    SaleStartedEvent.InputTuple,
    SaleStartedEvent.OutputTuple,
    SaleStartedEvent.OutputObject
  >;
  getEvent(
    key: "SparkPurchased"
  ): TypedContractEvent<
    SparkPurchasedEvent.InputTuple,
    SparkPurchasedEvent.OutputTuple,
    SparkPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "TokenLocked"
  ): TypedContractEvent<
    TokenLockedEvent.InputTuple,
    TokenLockedEvent.OutputTuple,
    TokenLockedEvent.OutputObject
  >;
  getEvent(
    key: "TokenUnlocked"
  ): TypedContractEvent<
    TokenUnlockedEvent.InputTuple,
    TokenUnlockedEvent.OutputTuple,
    TokenUnlockedEvent.OutputObject
  >;

  filters: {
    "BlacklistUpdated(address,bool)": TypedContractEvent<
      BlacklistUpdatedEvent.InputTuple,
      BlacklistUpdatedEvent.OutputTuple,
      BlacklistUpdatedEvent.OutputObject
    >;
    BlacklistUpdated: TypedContractEvent<
      BlacklistUpdatedEvent.InputTuple,
      BlacklistUpdatedEvent.OutputTuple,
      BlacklistUpdatedEvent.OutputObject
    >;

    "ComplianceCheck(address,bool)": TypedContractEvent<
      ComplianceCheckEvent.InputTuple,
      ComplianceCheckEvent.OutputTuple,
      ComplianceCheckEvent.OutputObject
    >;
    ComplianceCheck: TypedContractEvent<
      ComplianceCheckEvent.InputTuple,
      ComplianceCheckEvent.OutputTuple,
      ComplianceCheckEvent.OutputObject
    >;

    "DynamicPricingEnabled(bool)": TypedContractEvent<
      DynamicPricingEnabledEvent.InputTuple,
      DynamicPricingEnabledEvent.OutputTuple,
      DynamicPricingEnabledEvent.OutputObject
    >;
    DynamicPricingEnabled: TypedContractEvent<
      DynamicPricingEnabledEvent.InputTuple,
      DynamicPricingEnabledEvent.OutputTuple,
      DynamicPricingEnabledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PriceUpdated(uint256,uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "RevenueDistributed(uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      RevenueDistributedEvent.InputTuple,
      RevenueDistributedEvent.OutputTuple,
      RevenueDistributedEvent.OutputObject
    >;
    RevenueDistributed: TypedContractEvent<
      RevenueDistributedEvent.InputTuple,
      RevenueDistributedEvent.OutputTuple,
      RevenueDistributedEvent.OutputObject
    >;

    "SaleEnded()": TypedContractEvent<
      SaleEndedEvent.InputTuple,
      SaleEndedEvent.OutputTuple,
      SaleEndedEvent.OutputObject
    >;
    SaleEnded: TypedContractEvent<
      SaleEndedEvent.InputTuple,
      SaleEndedEvent.OutputTuple,
      SaleEndedEvent.OutputObject
    >;

    "SaleStarted(uint8)": TypedContractEvent<
      SaleStartedEvent.InputTuple,
      SaleStartedEvent.OutputTuple,
      SaleStartedEvent.OutputObject
    >;
    SaleStarted: TypedContractEvent<
      SaleStartedEvent.InputTuple,
      SaleStartedEvent.OutputTuple,
      SaleStartedEvent.OutputObject
    >;

    "SparkPurchased(address,uint256,uint8,uint256,bool)": TypedContractEvent<
      SparkPurchasedEvent.InputTuple,
      SparkPurchasedEvent.OutputTuple,
      SparkPurchasedEvent.OutputObject
    >;
    SparkPurchased: TypedContractEvent<
      SparkPurchasedEvent.InputTuple,
      SparkPurchasedEvent.OutputTuple,
      SparkPurchasedEvent.OutputObject
    >;

    "TokenLocked(address,uint256,uint256,bool)": TypedContractEvent<
      TokenLockedEvent.InputTuple,
      TokenLockedEvent.OutputTuple,
      TokenLockedEvent.OutputObject
    >;
    TokenLocked: TypedContractEvent<
      TokenLockedEvent.InputTuple,
      TokenLockedEvent.OutputTuple,
      TokenLockedEvent.OutputObject
    >;

    "TokenUnlocked(address,uint256)": TypedContractEvent<
      TokenUnlockedEvent.InputTuple,
      TokenUnlockedEvent.OutputTuple,
      TokenUnlockedEvent.OutputObject
    >;
    TokenUnlocked: TypedContractEvent<
      TokenUnlockedEvent.InputTuple,
      TokenUnlockedEvent.OutputTuple,
      TokenUnlockedEvent.OutputObject
    >;
  };
}
