/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LiquidityManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_LIQUIDITY_RATIO"
      | "LOCK_PERIOD"
      | "MAX_LIQUIDITY_RATIO"
      | "MIN_LIQUIDITY_RATIO"
      | "UNISWAP_V3_FACTORY_BASE"
      | "accumulatedFees"
      | "addLiquidity"
      | "afcToken"
      | "collectFees"
      | "emergencyWithdraw"
      | "getLiquidityHistoryLength"
      | "getLiquidityStatus"
      | "liquidityHistory"
      | "liquidityInitialized"
      | "liquidityRatio"
      | "liquidityUnlockTime"
      | "lpPool"
      | "marketMaker"
      | "marketMakerEnabled"
      | "owner"
      | "purchaseAFCFromLiquidity"
      | "rebalance"
      | "removeLiquidity"
      | "renounceOwnership"
      | "reserveLiquidity"
      | "reservedLiquidityAFC"
      | "reservedLiquidityUSDT"
      | "sellAFCToLiquidity"
      | "setLiquidityRatio"
      | "setMarketMaker"
      | "setMarketMakerEnabled"
      | "transferOwnership"
      | "usdtToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyWithdraw"
      | "FeesCollected"
      | "LiquidityAdded"
      | "LiquidityRatioUpdated"
      | "LiquidityRemoved"
      | "LiquidityReserved"
      | "MarketMakerEnabled"
      | "MarketMakerUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_LIQUIDITY_RATIO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_LIQUIDITY_RATIO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_LIQUIDITY_RATIO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UNISWAP_V3_FACTORY_BASE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accumulatedFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "afcToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "collectFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidityHistoryLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidityStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidityHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidityInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidityRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidityUnlockTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lpPool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "marketMaker",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marketMakerEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "purchaseAFCFromLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rebalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reservedLiquidityAFC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reservedLiquidityUSDT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellAFCToLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setLiquidityRatio",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketMaker",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketMakerEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdtToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_LIQUIDITY_RATIO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_LIQUIDITY_RATIO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_LIQUIDITY_RATIO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UNISWAP_V3_FACTORY_BASE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accumulatedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "afcToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidityHistoryLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidityStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidityHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidityInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidityRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidityUnlockTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketMaker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketMakerEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseAFCFromLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rebalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reservedLiquidityAFC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reservedLiquidityUSDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellAFCToLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLiquidityRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarketMaker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarketMakerEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdtToken", data: BytesLike): Result;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesCollectedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    afcAmount: BigNumberish,
    usdtAmount: BigNumberish,
    lpPool: AddressLike
  ];
  export type OutputTuple = [
    afcAmount: bigint,
    usdtAmount: bigint,
    lpPool: string
  ];
  export interface OutputObject {
    afcAmount: bigint;
    usdtAmount: bigint;
    lpPool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRatioUpdatedEvent {
  export type InputTuple = [oldRatio: BigNumberish, newRatio: BigNumberish];
  export type OutputTuple = [oldRatio: bigint, newRatio: bigint];
  export interface OutputObject {
    oldRatio: bigint;
    newRatio: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedEvent {
  export type InputTuple = [afcAmount: BigNumberish, usdtAmount: BigNumberish];
  export type OutputTuple = [afcAmount: bigint, usdtAmount: bigint];
  export interface OutputObject {
    afcAmount: bigint;
    usdtAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityReservedEvent {
  export type InputTuple = [afcAmount: BigNumberish, usdtAmount: BigNumberish];
  export type OutputTuple = [afcAmount: bigint, usdtAmount: bigint];
  export interface OutputObject {
    afcAmount: bigint;
    usdtAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketMakerEnabledEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketMakerUpdatedEvent {
  export type InputTuple = [oldAddress: AddressLike, newAddress: AddressLike];
  export type OutputTuple = [oldAddress: string, newAddress: string];
  export interface OutputObject {
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LiquidityManager extends BaseContract {
  connect(runner?: ContractRunner | null): LiquidityManager;
  waitForDeployment(): Promise<this>;

  interface: LiquidityManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_LIQUIDITY_RATIO: TypedContractMethod<[], [bigint], "view">;

  LOCK_PERIOD: TypedContractMethod<[], [bigint], "view">;

  MAX_LIQUIDITY_RATIO: TypedContractMethod<[], [bigint], "view">;

  MIN_LIQUIDITY_RATIO: TypedContractMethod<[], [bigint], "view">;

  UNISWAP_V3_FACTORY_BASE: TypedContractMethod<[], [string], "view">;

  accumulatedFees: TypedContractMethod<[], [bigint], "view">;

  addLiquidity: TypedContractMethod<
    [
      _lpPool: AddressLike,
      afcAmount: BigNumberish,
      usdtAmount: BigNumberish,
      minLiquidity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  afcToken: TypedContractMethod<[], [string], "view">;

  collectFees: TypedContractMethod<[], [void], "nonpayable">;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getLiquidityHistoryLength: TypedContractMethod<[], [bigint], "view">;

  getLiquidityStatus: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint] & {
        totalAfcLiquidity: bigint;
        totalUsdtLiquidity: bigint;
        availableAfc: bigint;
        availableUsdt: bigint;
        isInitialized: boolean;
        unlockTime: bigint;
      }
    ],
    "view"
  >;

  liquidityHistory: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string] & {
        timestamp: bigint;
        afcAmount: bigint;
        usdtAmount: bigint;
        provider: string;
      }
    ],
    "view"
  >;

  liquidityInitialized: TypedContractMethod<[], [boolean], "view">;

  liquidityRatio: TypedContractMethod<[], [bigint], "view">;

  liquidityUnlockTime: TypedContractMethod<[], [bigint], "view">;

  lpPool: TypedContractMethod<[], [string], "view">;

  marketMaker: TypedContractMethod<[], [string], "view">;

  marketMakerEnabled: TypedContractMethod<[], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  purchaseAFCFromLiquidity: TypedContractMethod<
    [afcAmount: BigNumberish, maxUsdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  rebalance: TypedContractMethod<
    [targetRatio: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeLiquidity: TypedContractMethod<
    [
      liquidityAmount: BigNumberish,
      minAfcAmount: BigNumberish,
      minUsdtAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reserveLiquidity: TypedContractMethod<
    [afcAmount: BigNumberish, usdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  reservedLiquidityAFC: TypedContractMethod<[], [bigint], "view">;

  reservedLiquidityUSDT: TypedContractMethod<[], [bigint], "view">;

  sellAFCToLiquidity: TypedContractMethod<
    [afcAmount: BigNumberish, minUsdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setLiquidityRatio: TypedContractMethod<
    [_ratio: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMarketMaker: TypedContractMethod<
    [_marketMaker: AddressLike],
    [void],
    "nonpayable"
  >;

  setMarketMakerEnabled: TypedContractMethod<
    [enabled: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdtToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_LIQUIDITY_RATIO"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_LIQUIDITY_RATIO"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_LIQUIDITY_RATIO"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UNISWAP_V3_FACTORY_BASE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "accumulatedFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [
      _lpPool: AddressLike,
      afcAmount: BigNumberish,
      usdtAmount: BigNumberish,
      minLiquidity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "afcToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "collectFees"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getLiquidityHistoryLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLiquidityStatus"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint] & {
        totalAfcLiquidity: bigint;
        totalUsdtLiquidity: bigint;
        availableAfc: bigint;
        availableUsdt: bigint;
        isInitialized: boolean;
        unlockTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "liquidityHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string] & {
        timestamp: bigint;
        afcAmount: bigint;
        usdtAmount: bigint;
        provider: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "liquidityInitialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "liquidityRatio"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidityUnlockTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lpPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "marketMaker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "marketMakerEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseAFCFromLiquidity"
  ): TypedContractMethod<
    [afcAmount: BigNumberish, maxUsdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rebalance"
  ): TypedContractMethod<[targetRatio: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<
    [
      liquidityAmount: BigNumberish,
      minAfcAmount: BigNumberish,
      minUsdtAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reserveLiquidity"
  ): TypedContractMethod<
    [afcAmount: BigNumberish, usdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reservedLiquidityAFC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reservedLiquidityUSDT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "sellAFCToLiquidity"
  ): TypedContractMethod<
    [afcAmount: BigNumberish, minUsdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setLiquidityRatio"
  ): TypedContractMethod<[_ratio: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMarketMaker"
  ): TypedContractMethod<[_marketMaker: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMarketMakerEnabled"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdtToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "FeesCollected"
  ): TypedContractEvent<
    FeesCollectedEvent.InputTuple,
    FeesCollectedEvent.OutputTuple,
    FeesCollectedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRatioUpdated"
  ): TypedContractEvent<
    LiquidityRatioUpdatedEvent.InputTuple,
    LiquidityRatioUpdatedEvent.OutputTuple,
    LiquidityRatioUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemoved"
  ): TypedContractEvent<
    LiquidityRemovedEvent.InputTuple,
    LiquidityRemovedEvent.OutputTuple,
    LiquidityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityReserved"
  ): TypedContractEvent<
    LiquidityReservedEvent.InputTuple,
    LiquidityReservedEvent.OutputTuple,
    LiquidityReservedEvent.OutputObject
  >;
  getEvent(
    key: "MarketMakerEnabled"
  ): TypedContractEvent<
    MarketMakerEnabledEvent.InputTuple,
    MarketMakerEnabledEvent.OutputTuple,
    MarketMakerEnabledEvent.OutputObject
  >;
  getEvent(
    key: "MarketMakerUpdated"
  ): TypedContractEvent<
    MarketMakerUpdatedEvent.InputTuple,
    MarketMakerUpdatedEvent.OutputTuple,
    MarketMakerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "EmergencyWithdraw(address,address,uint256)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "FeesCollected(uint256)": TypedContractEvent<
      FeesCollectedEvent.InputTuple,
      FeesCollectedEvent.OutputTuple,
      FeesCollectedEvent.OutputObject
    >;
    FeesCollected: TypedContractEvent<
      FeesCollectedEvent.InputTuple,
      FeesCollectedEvent.OutputTuple,
      FeesCollectedEvent.OutputObject
    >;

    "LiquidityAdded(uint256,uint256,address)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "LiquidityRatioUpdated(uint256,uint256)": TypedContractEvent<
      LiquidityRatioUpdatedEvent.InputTuple,
      LiquidityRatioUpdatedEvent.OutputTuple,
      LiquidityRatioUpdatedEvent.OutputObject
    >;
    LiquidityRatioUpdated: TypedContractEvent<
      LiquidityRatioUpdatedEvent.InputTuple,
      LiquidityRatioUpdatedEvent.OutputTuple,
      LiquidityRatioUpdatedEvent.OutputObject
    >;

    "LiquidityRemoved(uint256,uint256)": TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
    LiquidityRemoved: TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;

    "LiquidityReserved(uint256,uint256)": TypedContractEvent<
      LiquidityReservedEvent.InputTuple,
      LiquidityReservedEvent.OutputTuple,
      LiquidityReservedEvent.OutputObject
    >;
    LiquidityReserved: TypedContractEvent<
      LiquidityReservedEvent.InputTuple,
      LiquidityReservedEvent.OutputTuple,
      LiquidityReservedEvent.OutputObject
    >;

    "MarketMakerEnabled(bool)": TypedContractEvent<
      MarketMakerEnabledEvent.InputTuple,
      MarketMakerEnabledEvent.OutputTuple,
      MarketMakerEnabledEvent.OutputObject
    >;
    MarketMakerEnabled: TypedContractEvent<
      MarketMakerEnabledEvent.InputTuple,
      MarketMakerEnabledEvent.OutputTuple,
      MarketMakerEnabledEvent.OutputObject
    >;

    "MarketMakerUpdated(address,address)": TypedContractEvent<
      MarketMakerUpdatedEvent.InputTuple,
      MarketMakerUpdatedEvent.OutputTuple,
      MarketMakerUpdatedEvent.OutputObject
    >;
    MarketMakerUpdated: TypedContractEvent<
      MarketMakerUpdatedEvent.InputTuple,
      MarketMakerUpdatedEvent.OutputTuple,
      MarketMakerUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
