/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Spark_NFT {
  export type SparkAttributesStruct = {
    level: BigNumberish;
    avatarType: BigNumberish;
    computeLevel: BigNumberish;
    aiNickname: string;
    metadataURI: string;
    mintedAt: BigNumberish;
  };

  export type SparkAttributesStructOutput = [
    level: bigint,
    avatarType: bigint,
    computeLevel: bigint,
    aiNickname: string,
    metadataURI: string,
    mintedAt: bigint
  ] & {
    level: bigint;
    avatarType: bigint;
    computeLevel: bigint;
    aiNickname: string;
    metadataURI: string;
    mintedAt: bigint;
  };

  export type StakeInfoStruct = {
    tokenId: BigNumberish;
    staker: AddressLike;
    stakedAt: BigNumberish;
    unlockTime: BigNumberish;
    status: BigNumberish;
    isWrapped: boolean;
  };

  export type StakeInfoStructOutput = [
    tokenId: bigint,
    staker: string,
    stakedAt: bigint,
    unlockTime: bigint,
    status: bigint,
    isWrapped: boolean
  ] & {
    tokenId: bigint;
    staker: string;
    stakedAt: bigint;
    unlockTime: bigint;
    status: bigint;
    isWrapped: boolean;
  };
}

export interface Spark_NFTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CORE_LOCK_PERIOD"
      | "CORE_NODE_PRICE"
      | "MAX_CORE_NODES"
      | "MAX_REGULAR_NODES"
      | "MAX_SUB_NODES"
      | "REGULAR_LOCK_PERIOD"
      | "REGULAR_NODE_PRICE"
      | "SUB_LOCK_PERIOD"
      | "SUB_NODE_PRICE"
      | "afcTokenAddress"
      | "approve"
      | "balanceOf"
      | "balanceOfByLevel"
      | "batchMint"
      | "bindNodeIdentity"
      | "burn"
      | "coreNodeCount"
      | "coreNodeMintingOpen"
      | "emergencyUnstake"
      | "emergencyWithdraw"
      | "getApproved"
      | "getQuotaStatus"
      | "getSparkAttributes"
      | "getStakeInfo"
      | "getUserSparkCount"
      | "isApprovedForAll"
      | "isTransferable"
      | "mintCoreNode"
      | "mintRegularNode"
      | "mintSubNode"
      | "name"
      | "owner"
      | "ownerOf"
      | "regularNodeCount"
      | "regularNodeMintingOpen"
      | "renounceOwnership"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setAFCTokenAddress"
      | "setApprovalForAll"
      | "setMintingStatus"
      | "sparkAttributes"
      | "stake"
      | "stakeInfo"
      | "subNodeCount"
      | "subNodeMintingOpen"
      | "supportsInterface"
      | "symbol"
      | "tokenURI"
      | "transferFrom"
      | "transferOwnership"
      | "unstake"
      | "updateAttributes"
      | "upgradeLevel"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "BatchMetadataUpdate"
      | "MetadataUpdate"
      | "NodeIdentityBound"
      | "OwnershipTransferred"
      | "QuotaUpdated"
      | "SparkAttributesUpdated"
      | "SparkLevelUpgraded"
      | "SparkMinted"
      | "SparkStaked"
      | "SparkUnstaked"
      | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CORE_LOCK_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CORE_NODE_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_CORE_NODES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_REGULAR_NODES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SUB_NODES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REGULAR_LOCK_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REGULAR_NODE_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUB_LOCK_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUB_NODE_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "afcTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfByLevel",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchMint",
    values: [
      AddressLike[],
      BigNumberish[],
      BigNumberish[],
      BigNumberish[],
      string[],
      string[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "bindNodeIdentity",
    values: [BigNumberish, AddressLike, string]
  ): string;
  encodeFunctionData(functionFragment: "burn", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "coreNodeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "coreNodeMintingOpen",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyUnstake",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuotaStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSparkAttributes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStakeInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSparkCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTransferable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintCoreNode",
    values: [AddressLike, BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintRegularNode",
    values: [AddressLike, BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintSubNode",
    values: [AddressLike, BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "regularNodeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "regularNodeMintingOpen",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAFCTokenAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMintingStatus",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "sparkAttributes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subNodeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "subNodeMintingOpen",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAttributes",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeLevel",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CORE_LOCK_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CORE_NODE_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_CORE_NODES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_REGULAR_NODES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SUB_NODES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REGULAR_LOCK_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REGULAR_NODE_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUB_LOCK_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUB_NODE_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afcTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfByLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "batchMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bindNodeIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "coreNodeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "coreNodeMintingOpen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyUnstake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuotaStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSparkAttributes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSparkCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTransferable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintCoreNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintRegularNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintSubNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "regularNodeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "regularNodeMintingOpen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAFCTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMintingStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sparkAttributes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakeInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subNodeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subNodeMintingOpen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAttributes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeLevel",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchMetadataUpdateEvent {
  export type InputTuple = [
    _fromTokenId: BigNumberish,
    _toTokenId: BigNumberish
  ];
  export type OutputTuple = [_fromTokenId: bigint, _toTokenId: bigint];
  export interface OutputObject {
    _fromTokenId: bigint;
    _toTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetadataUpdateEvent {
  export type InputTuple = [_tokenId: BigNumberish];
  export type OutputTuple = [_tokenId: bigint];
  export interface OutputObject {
    _tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeIdentityBoundEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    nodeAddress: AddressLike,
    nodeRegion: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    nodeAddress: string,
    nodeRegion: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    nodeAddress: string;
    nodeRegion: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuotaUpdatedEvent {
  export type InputTuple = [level: BigNumberish, open: boolean];
  export type OutputTuple = [level: bigint, open: boolean];
  export interface OutputObject {
    level: bigint;
    open: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SparkAttributesUpdatedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    aiNickname: string,
    metadataURI: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    aiNickname: string,
    metadataURI: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    aiNickname: string;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SparkLevelUpgradedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    oldLevel: BigNumberish,
    newLevel: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    oldLevel: bigint,
    newLevel: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    oldLevel: bigint;
    newLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SparkMintedEvent {
  export type InputTuple = [
    to: AddressLike,
    tokenId: BigNumberish,
    level: BigNumberish,
    avatarType: BigNumberish,
    computeLevel: BigNumberish
  ];
  export type OutputTuple = [
    to: string,
    tokenId: bigint,
    level: bigint,
    avatarType: bigint,
    computeLevel: bigint
  ];
  export interface OutputObject {
    to: string;
    tokenId: bigint;
    level: bigint;
    avatarType: bigint;
    computeLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SparkStakedEvent {
  export type InputTuple = [
    staker: AddressLike,
    tokenId: BigNumberish,
    unlockTime: BigNumberish
  ];
  export type OutputTuple = [
    staker: string,
    tokenId: bigint,
    unlockTime: bigint
  ];
  export interface OutputObject {
    staker: string;
    tokenId: bigint;
    unlockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SparkUnstakedEvent {
  export type InputTuple = [
    staker: AddressLike,
    tokenId: BigNumberish,
    stakedDuration: BigNumberish
  ];
  export type OutputTuple = [
    staker: string,
    tokenId: bigint,
    stakedDuration: bigint
  ];
  export interface OutputObject {
    staker: string;
    tokenId: bigint;
    stakedDuration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Spark_NFT extends BaseContract {
  connect(runner?: ContractRunner | null): Spark_NFT;
  waitForDeployment(): Promise<this>;

  interface: Spark_NFTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CORE_LOCK_PERIOD: TypedContractMethod<[], [bigint], "view">;

  CORE_NODE_PRICE: TypedContractMethod<[], [bigint], "view">;

  MAX_CORE_NODES: TypedContractMethod<[], [bigint], "view">;

  MAX_REGULAR_NODES: TypedContractMethod<[], [bigint], "view">;

  MAX_SUB_NODES: TypedContractMethod<[], [bigint], "view">;

  REGULAR_LOCK_PERIOD: TypedContractMethod<[], [bigint], "view">;

  REGULAR_NODE_PRICE: TypedContractMethod<[], [bigint], "view">;

  SUB_LOCK_PERIOD: TypedContractMethod<[], [bigint], "view">;

  SUB_NODE_PRICE: TypedContractMethod<[], [bigint], "view">;

  afcTokenAddress: TypedContractMethod<[], [string], "view">;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  balanceOfByLevel: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  batchMint: TypedContractMethod<
    [
      recipients: AddressLike[],
      levels: BigNumberish[],
      avatarTypes: BigNumberish[],
      computeLevels: BigNumberish[],
      aiNicknames: string[],
      metadataURIs: string[]
    ],
    [void],
    "nonpayable"
  >;

  bindNodeIdentity: TypedContractMethod<
    [tokenId: BigNumberish, nodeAddress: AddressLike, nodeRegion: string],
    [void],
    "nonpayable"
  >;

  burn: TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;

  coreNodeCount: TypedContractMethod<[], [bigint], "view">;

  coreNodeMintingOpen: TypedContractMethod<[], [boolean], "view">;

  emergencyUnstake: TypedContractMethod<
    [tokenId: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getQuotaStatus: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        coreAvailable: bigint;
        subAvailable: bigint;
        regularAvailable: bigint;
      }
    ],
    "view"
  >;

  getSparkAttributes: TypedContractMethod<
    [tokenId: BigNumberish],
    [Spark_NFT.SparkAttributesStructOutput],
    "view"
  >;

  getStakeInfo: TypedContractMethod<
    [tokenId: BigNumberish],
    [Spark_NFT.StakeInfoStructOutput],
    "view"
  >;

  getUserSparkCount: TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint, bigint] & { core: bigint; sub: bigint; regular: bigint }],
    "view"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  isTransferable: TypedContractMethod<
    [tokenId: BigNumberish],
    [boolean],
    "view"
  >;

  mintCoreNode: TypedContractMethod<
    [
      to: AddressLike,
      avatarType: BigNumberish,
      computeLevel: BigNumberish,
      aiNickname: string,
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;

  mintRegularNode: TypedContractMethod<
    [
      to: AddressLike,
      avatarType: BigNumberish,
      computeLevel: BigNumberish,
      aiNickname: string,
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;

  mintSubNode: TypedContractMethod<
    [
      to: AddressLike,
      avatarType: BigNumberish,
      computeLevel: BigNumberish,
      aiNickname: string,
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  regularNodeCount: TypedContractMethod<[], [bigint], "view">;

  regularNodeMintingOpen: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setAFCTokenAddress: TypedContractMethod<
    [_afcTokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setMintingStatus: TypedContractMethod<
    [level: BigNumberish, open: boolean],
    [void],
    "nonpayable"
  >;

  sparkAttributes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string, string, bigint] & {
        level: bigint;
        avatarType: bigint;
        computeLevel: bigint;
        aiNickname: string;
        metadataURI: string;
        mintedAt: bigint;
      }
    ],
    "view"
  >;

  stake: TypedContractMethod<
    [tokenId: BigNumberish, isWrapped: boolean],
    [void],
    "nonpayable"
  >;

  stakeInfo: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, boolean] & {
        tokenId: bigint;
        staker: string;
        stakedAt: bigint;
        unlockTime: bigint;
        status: bigint;
        isWrapped: boolean;
      }
    ],
    "view"
  >;

  subNodeCount: TypedContractMethod<[], [bigint], "view">;

  subNodeMintingOpen: TypedContractMethod<[], [boolean], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unstake: TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;

  updateAttributes: TypedContractMethod<
    [tokenId: BigNumberish, aiNickname: string, metadataURI: string],
    [void],
    "nonpayable"
  >;

  upgradeLevel: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CORE_LOCK_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CORE_NODE_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_CORE_NODES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_REGULAR_NODES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SUB_NODES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REGULAR_LOCK_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REGULAR_NODE_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SUB_LOCK_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SUB_NODE_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "afcTokenAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOfByLevel"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchMint"
  ): TypedContractMethod<
    [
      recipients: AddressLike[],
      levels: BigNumberish[],
      avatarTypes: BigNumberish[],
      computeLevels: BigNumberish[],
      aiNicknames: string[],
      metadataURIs: string[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bindNodeIdentity"
  ): TypedContractMethod<
    [tokenId: BigNumberish, nodeAddress: AddressLike, nodeRegion: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "coreNodeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "coreNodeMintingOpen"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "emergencyUnstake"
  ): TypedContractMethod<
    [tokenId: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getQuotaStatus"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        coreAvailable: bigint;
        subAvailable: bigint;
        regularAvailable: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSparkAttributes"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [Spark_NFT.SparkAttributesStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStakeInfo"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [Spark_NFT.StakeInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserSparkCount"
  ): TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint, bigint] & { core: bigint; sub: bigint; regular: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTransferable"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "mintCoreNode"
  ): TypedContractMethod<
    [
      to: AddressLike,
      avatarType: BigNumberish,
      computeLevel: BigNumberish,
      aiNickname: string,
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintRegularNode"
  ): TypedContractMethod<
    [
      to: AddressLike,
      avatarType: BigNumberish,
      computeLevel: BigNumberish,
      aiNickname: string,
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintSubNode"
  ): TypedContractMethod<
    [
      to: AddressLike,
      avatarType: BigNumberish,
      computeLevel: BigNumberish,
      aiNickname: string,
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "regularNodeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "regularNodeMintingOpen"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAFCTokenAddress"
  ): TypedContractMethod<[_afcTokenAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMintingStatus"
  ): TypedContractMethod<
    [level: BigNumberish, open: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sparkAttributes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string, string, bigint] & {
        level: bigint;
        avatarType: bigint;
        computeLevel: bigint;
        aiNickname: string;
        metadataURI: string;
        mintedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<
    [tokenId: BigNumberish, isWrapped: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakeInfo"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, boolean] & {
        tokenId: bigint;
        staker: string;
        stakedAt: bigint;
        unlockTime: bigint;
        status: bigint;
        isWrapped: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "subNodeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "subNodeMintingOpen"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAttributes"
  ): TypedContractMethod<
    [tokenId: BigNumberish, aiNickname: string, metadataURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeLevel"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "BatchMetadataUpdate"
  ): TypedContractEvent<
    BatchMetadataUpdateEvent.InputTuple,
    BatchMetadataUpdateEvent.OutputTuple,
    BatchMetadataUpdateEvent.OutputObject
  >;
  getEvent(
    key: "MetadataUpdate"
  ): TypedContractEvent<
    MetadataUpdateEvent.InputTuple,
    MetadataUpdateEvent.OutputTuple,
    MetadataUpdateEvent.OutputObject
  >;
  getEvent(
    key: "NodeIdentityBound"
  ): TypedContractEvent<
    NodeIdentityBoundEvent.InputTuple,
    NodeIdentityBoundEvent.OutputTuple,
    NodeIdentityBoundEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "QuotaUpdated"
  ): TypedContractEvent<
    QuotaUpdatedEvent.InputTuple,
    QuotaUpdatedEvent.OutputTuple,
    QuotaUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SparkAttributesUpdated"
  ): TypedContractEvent<
    SparkAttributesUpdatedEvent.InputTuple,
    SparkAttributesUpdatedEvent.OutputTuple,
    SparkAttributesUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SparkLevelUpgraded"
  ): TypedContractEvent<
    SparkLevelUpgradedEvent.InputTuple,
    SparkLevelUpgradedEvent.OutputTuple,
    SparkLevelUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "SparkMinted"
  ): TypedContractEvent<
    SparkMintedEvent.InputTuple,
    SparkMintedEvent.OutputTuple,
    SparkMintedEvent.OutputObject
  >;
  getEvent(
    key: "SparkStaked"
  ): TypedContractEvent<
    SparkStakedEvent.InputTuple,
    SparkStakedEvent.OutputTuple,
    SparkStakedEvent.OutputObject
  >;
  getEvent(
    key: "SparkUnstaked"
  ): TypedContractEvent<
    SparkUnstakedEvent.InputTuple,
    SparkUnstakedEvent.OutputTuple,
    SparkUnstakedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "BatchMetadataUpdate(uint256,uint256)": TypedContractEvent<
      BatchMetadataUpdateEvent.InputTuple,
      BatchMetadataUpdateEvent.OutputTuple,
      BatchMetadataUpdateEvent.OutputObject
    >;
    BatchMetadataUpdate: TypedContractEvent<
      BatchMetadataUpdateEvent.InputTuple,
      BatchMetadataUpdateEvent.OutputTuple,
      BatchMetadataUpdateEvent.OutputObject
    >;

    "MetadataUpdate(uint256)": TypedContractEvent<
      MetadataUpdateEvent.InputTuple,
      MetadataUpdateEvent.OutputTuple,
      MetadataUpdateEvent.OutputObject
    >;
    MetadataUpdate: TypedContractEvent<
      MetadataUpdateEvent.InputTuple,
      MetadataUpdateEvent.OutputTuple,
      MetadataUpdateEvent.OutputObject
    >;

    "NodeIdentityBound(uint256,address,string)": TypedContractEvent<
      NodeIdentityBoundEvent.InputTuple,
      NodeIdentityBoundEvent.OutputTuple,
      NodeIdentityBoundEvent.OutputObject
    >;
    NodeIdentityBound: TypedContractEvent<
      NodeIdentityBoundEvent.InputTuple,
      NodeIdentityBoundEvent.OutputTuple,
      NodeIdentityBoundEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "QuotaUpdated(uint8,bool)": TypedContractEvent<
      QuotaUpdatedEvent.InputTuple,
      QuotaUpdatedEvent.OutputTuple,
      QuotaUpdatedEvent.OutputObject
    >;
    QuotaUpdated: TypedContractEvent<
      QuotaUpdatedEvent.InputTuple,
      QuotaUpdatedEvent.OutputTuple,
      QuotaUpdatedEvent.OutputObject
    >;

    "SparkAttributesUpdated(uint256,string,string)": TypedContractEvent<
      SparkAttributesUpdatedEvent.InputTuple,
      SparkAttributesUpdatedEvent.OutputTuple,
      SparkAttributesUpdatedEvent.OutputObject
    >;
    SparkAttributesUpdated: TypedContractEvent<
      SparkAttributesUpdatedEvent.InputTuple,
      SparkAttributesUpdatedEvent.OutputTuple,
      SparkAttributesUpdatedEvent.OutputObject
    >;

    "SparkLevelUpgraded(uint256,uint8,uint8)": TypedContractEvent<
      SparkLevelUpgradedEvent.InputTuple,
      SparkLevelUpgradedEvent.OutputTuple,
      SparkLevelUpgradedEvent.OutputObject
    >;
    SparkLevelUpgraded: TypedContractEvent<
      SparkLevelUpgradedEvent.InputTuple,
      SparkLevelUpgradedEvent.OutputTuple,
      SparkLevelUpgradedEvent.OutputObject
    >;

    "SparkMinted(address,uint256,uint8,uint8,uint8)": TypedContractEvent<
      SparkMintedEvent.InputTuple,
      SparkMintedEvent.OutputTuple,
      SparkMintedEvent.OutputObject
    >;
    SparkMinted: TypedContractEvent<
      SparkMintedEvent.InputTuple,
      SparkMintedEvent.OutputTuple,
      SparkMintedEvent.OutputObject
    >;

    "SparkStaked(address,uint256,uint256)": TypedContractEvent<
      SparkStakedEvent.InputTuple,
      SparkStakedEvent.OutputTuple,
      SparkStakedEvent.OutputObject
    >;
    SparkStaked: TypedContractEvent<
      SparkStakedEvent.InputTuple,
      SparkStakedEvent.OutputTuple,
      SparkStakedEvent.OutputObject
    >;

    "SparkUnstaked(address,uint256,uint256)": TypedContractEvent<
      SparkUnstakedEvent.InputTuple,
      SparkUnstakedEvent.OutputTuple,
      SparkUnstakedEvent.OutputObject
    >;
    SparkUnstaked: TypedContractEvent<
      SparkUnstakedEvent.InputTuple,
      SparkUnstakedEvent.OutputTuple,
      SparkUnstakedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
