"""
AI Services
云端 API 服务模块（轨道 A + 轨道 B）
"""
from .base import BaseAIService, AIServiceConfig

# 延迟导入重型依赖（langchain_openai 等），避免 wallet_main.py 等轻量模块触发不必要的导入
def _lazy_import(name):
    import importlib
    return importlib.import_module(f".{name}", __package__)

def __getattr__(name):
    _lazy_map = {
        "OpenAIService": "openai_service",
        "AnthropicService": "anthropic_service",
        "DeepSeekService": "deepseek_service",
        "AIRouter": "router",
        "ModelProvider": "router",
        "LoadBalancingStrategy": "router",
        "APIKeyManager": "api_key_manager",
        "KeyTier": "api_key_manager",
        # 轨道 B
        "OllamaService": "ollama_service",
        "LocalModel": "ollama_service",
        "ModelSize": "ollama_service",
        "ModelFamily": "ollama_service",
        "ModelStatus": "ollama_service",
        "OllamaGenerateRequest": "ollama_service",
        "OllamaChatMessage": "ollama_service",
        "OllamaResponse": "ollama_service",
        "VLLMService": "vllm_service",
        "VLLMModel": "vllm_service",
        "SamplingParams": "vllm_service",
        "CompletionRequest": "vllm_service",
        "VLLMChatMessage": "vllm_service",
        "CompletionResponse": "vllm_service",
        "ChatCompletionResponse": "vllm_service",
        "LocalModelRouter": "local_model_router",
        "LocalModelProvider": "local_model_router",
        "ModelLoadStrategy": "local_model_router",
        "LocalModelRequest": "local_model_router",
        "LocalModelResponse": "local_model_router",
        # LangChain
        "RAGService": "rag_service",
        "RAGConfig": "rag_service",
        "VectorStoreType": "rag_service",
        "EmbeddingModel": "rag_service",
        "DocumentProcessor": "rag_service",
        "EmbeddingService": "rag_service",
        "VectorStoreManager": "rag_service",
        "TaskOrchestrator": "task_orchestration",
        "TaskConfig": "task_orchestration",
        "TaskResult": "task_orchestration",
        "TaskType": "task_orchestration",
        "TaskStatus": "task_orchestration",
        "Priority": "task_orchestration",
        "TaskChainBuilder": "task_orchestration",
        "TaskAgentBuilder": "task_orchestration",
        # 情感计算
        "EmotionalComputingService": "emotional_computing",
        "EmotionalMemory": "emotional_computing",
        "EmotionType": "emotional_computing",
        "EmotionalTone": "emotional_computing",
        "EmotionScore": "emotional_computing",
        "EmotionalAnalysis": "emotional_computing",
        "EmotionalResponse": "emotional_computing",
        # 知识库
        "KnowledgeBaseQAService": "knowledge_base",
        "KnowledgeBaseManager": "knowledge_base",
        "KnowledgeEntry": "knowledge_base",
        "KnowledgeCategory": "knowledge_base",
        "AnswerConfidence": "knowledge_base",
        "QAResult": "knowledge_base",
        "Web4KnowledgeSeeder": "knowledge_base",
        # 内容安全
        "ContentSafetyService": "content_safety",
        "ContentSafetyConfig": "content_safety",
        "ViolationHandler": "content_safety",
        "SafetyLevel": "content_safety",
        "ViolationType": "content_safety",
        "SafetyViolation": "content_safety",
        "ContentSafetyResult": "content_safety",
        "EmotionalSafetyResult": "content_safety",
        "SafetyWrapper": "safety_wrapper",
        "SafetyCheckResult": "safety_wrapper",
        "create_safe_service": "safety_wrapper",
        # 训练数据
        "Web4DataCollector": "training_data_collector",
        "TrainingDataAugmenter": "training_data_collector",
        "TrainingDataItem": "training_data_collector",
        "DataCollectionConfig": "training_data_collector",
        "DataSourceType": "training_data_collector",
        "DataQualityLevel": "training_data_collector",
        "FineTuningService": "fine_tuning_service",
        "Web4ModelManager": "fine_tuning_service",
        "FineTuningConfig": "fine_tuning_service",
        "FineTuningResult": "fine_tuning_service",
        "TrainingProgress": "fine_tuning_service",
        "FineTuningProvider": "fine_tuning_service",
        "TrainingStage": "fine_tuning_service",
        "QualityVerifier": "quality_verifier",
        "ModelQualityMonitor": "quality_verifier",
        "QualityScore": "quality_verifier",
        "VerificationResult": "quality_verifier",
        "QualityReport": "quality_verifier",
        "TestCase": "quality_verifier",
        "QualityMetric": "quality_verifier",
        "QualityLevel": "quality_verifier",
        "KnowledgeBaseUpdater": "knowledge_base_updater",
        "KnowledgeBaseVersionManager": "knowledge_base_updater",
        "KnowledgeBaseScheduler": "knowledge_base_updater",
        "UpdateConfig": "knowledge_base_updater",
        "UpdateResult": "knowledge_base_updater",
        "UpdateProgress": "knowledge_base_updater",
        "KnowledgeVersion": "knowledge_base_updater",
        "UpdateType": "knowledge_base_updater",
        "UpdateStatus": "knowledge_base_updater",
    }
    if name in _lazy_map:
        mod = _lazy_import(_lazy_map[name])
        return getattr(mod, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

__all__ = [
    # 轨道 A：云端 API
    "BaseAIService",
    "AIServiceConfig",
    "OpenAIService",
    "AnthropicService",
    "DeepSeekService",
    "AIRouter",
    "ModelProvider",
    "LoadBalancingStrategy",
    "APIKeyManager",
    "KeyTier",
    # 轨道 B：本地模型
    "OllamaService",
    "LocalModel",
    "ModelSize",
    "ModelFamily",
    "ModelStatus",
    "OllamaGenerateRequest",
    "OllamaChatMessage",
    "OllamaResponse",
    "VLLMService",
    "VLLMModel",
    "SamplingParams",
    "CompletionRequest",
    "VLLMChatMessage",
    "CompletionResponse",
    "ChatCompletionResponse",
    "LocalModelRouter",
    "LocalModelProvider",
    "ModelLoadStrategy",
    "LocalModelRequest",
    "LocalModelResponse",
    # LangChain 任务编排与 RAG
    "RAGService",
    "RAGConfig",
    "VectorStoreType",
    "EmbeddingModel",
    "DocumentProcessor",
    "EmbeddingService",
    "VectorStoreManager",
    "TaskOrchestrator",
    "TaskConfig",
    "TaskResult",
    "TaskType",
    "TaskStatus",
    "Priority",
    "TaskChainBuilder",
    "TaskAgentBuilder",
    # 情感计算
    "EmotionalComputingService",
    "EmotionalMemory",
    "EmotionType",
    "EmotionalTone",
    "EmotionScore",
    "EmotionalAnalysis",
    "EmotionalResponse",
    # 知识库问答
    "KnowledgeBaseQAService",
    "KnowledgeBaseManager",
    "KnowledgeEntry",
    "KnowledgeCategory",
    "AnswerConfidence",
    "QAResult",
    "Web4KnowledgeSeeder",
    # AI 内容安全过滤
    "ContentSafetyService",
    "ContentSafetyConfig",
    "ViolationHandler",
    "SafetyLevel",
    "ViolationType",
    "SafetyViolation",
    "ContentSafetyResult",
    "EmotionalSafetyResult",
    "SafetyWrapper",
    "SafetyCheckResult",
    "create_safe_service",
    # Web4 知识库训练数据准备
    "Web4DataCollector",
    "TrainingDataAugmenter",
    "TrainingDataItem",
    "DataCollectionConfig",
    "DataSourceType",
    "DataQualityLevel",
    "FineTuningService",
    "Web4ModelManager",
    "FineTuningConfig",
    "FineTuningResult",
    "TrainingProgress",
    "FineTuningProvider",
    "ModelSize",
    "TrainingStage",
    "QualityVerifier",
    "ModelQualityMonitor",
    "QualityScore",
    "VerificationResult",
    "QualityReport",
    "TestCase",
    "QualityMetric",
    "QualityLevel",
    "KnowledgeBaseUpdater",
    "KnowledgeBaseVersionManager",
    "KnowledgeBaseScheduler",
    "UpdateConfig",
    "UpdateResult",
    "UpdateProgress",
    "KnowledgeVersion",
    "UpdateType",
    "UpdateStatus",
]